#!/bin/bash
holidays = ['3112','0101','0201','0701','2302','0803','0105','0905']
if [[ `grep $PAM_USER /etc/group | grep 'admin'` ]]
then exit 0
fi
if [[ `date +%u` > 5 ]]
then exit 1
elif [[ " ${holidays[*]} " == *" date +%d%m "* ]]
then exit 1
else exit 0
fi
