---
#- hosts: all
#  become_method: sudo
#  tasks:

- hosts: inetrouter.otus.lan
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for inetRouter
    shell: |
            iptables-restore < /vagrant/iptables-inetRouter
            ip route add 192.168.0.0/16 via 192.168.255.2

- hosts: centralrouter.otus.lan
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for centralRouter
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.255.1"
            nmcli connection modify "System eth5" +ipv4.routes "192.168.2.0/24 192.168.254.2"
            nmcli connection modify "System eth6" +ipv4.routes "192.168.1.0/24 192.168.253.2"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
            nmcli connection up "System eth5"
            nmcli connection up "System eth6"

- hosts: centralserver.otus.lan
  become: yes
  tasks:
  - name: Installing epel-release
    yum:
            name: epel-release
            state: latest
  - name: Installing ipa-server and expect
    yum:
            name: "{{ packages }}"
    vars:
            packages:
            - ipa-server
            - ipa-server-dns
            - expect

  - lineinfile:
          path: /etc/selinux/config
          regexp: 'SELINUX=enforcing'
          line: 'SELINUX=disabled'

  - name: Stop SELinux
    shell: |
            setenforce 0

  - lineinfile:
          path: /etc/hosts
          regexp: 'centralserver'
          line: '192.168.0.2       centralserver.otus.lan  centralserver'

  - name: Configure ipa-server
    shell: |
            spawn ipa-server-install

            expect "Do you want to configure integrated DNS"
            send "yes\n"

            expect "Server host name"
            send "\n"

            expect "Please confirm the domain name"
            send "\n"

            expect "Please provide a realm name"
            send "\n"

            expect "Directory Manager password"
            send "OtusPassWord\n"

            expect "Password (confirm)"
            send "OtusPassWord\n"

            expect "IPA admin password"
            send "OtusPassWord\n"

            expect "Password (confirm)"
            send "OtusPassWord\n"

            expect "Do you want to configure DNS forwarders"
            send "yes\n"

            expect "Do you want to configure these servers as DNS forwarders"
            send "yes\n"

            expect "Enter an IP address for a DNS forwarder, or press Enter to skip"
            send "\n"

            expect "Do you want to search for missing reverse zones"
            send "yes\n"

            expect "Continue to configure the system with these values"
            send "yes\n"

            expect "Continue to configure the system with these values"
            send "yes\n"
    args:
            executable: /usr/bin/expect

  - name: Running ipa-server-upgrade
    shell: |
            ipa-server-upgrade
    args:
            executable: /bin/bash

  - name: Running commands for centralServer
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.0.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
    args:
            executable: /bin/bash

- hosts: office1router.otus.lan
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for office1Router
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth5" ipv4.gateway "192.168.254.1"
            nmcli connection modify "System eth5" +ipv4.routes "192.168.0.0/24 192.168.254.1"
            nmcli connection modify "System eth5" +ipv4.routes "192.168.1.0/24 192.168.254.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth5"
    args:
            executable: /bin/bash
            
- hosts: office1server.otus.lan
  become: yes
  tasks:
  - name: Running commands for office1Server
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.2.193"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
    args:
            executable: /bin/bash
            
- hosts: office2router.otus.lan
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for office2Router
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth4" ipv4.gateway "192.168.253.1"
            nmcli connection modify "System eth4" +ipv4.routes "192.168.0.0/24 192.168.253.1"
            nmcli connection modify "System eth4" +ipv4.routes "192.168.2.0/24 192.168.253.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth4"
    args:
            executable: /bin/bash
            
- hosts: office2server.otus.lan
  become: yes
  tasks:
  - name: Running commands for office2Server
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.1.193"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
    args:
            executable: /bin/bash

