---
#- hosts: all
#  become_method: sudo
#  tasks:

- hosts: inetRouter
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for inetRouter
    shell: |
            iptables-restore < /vagrant/iptables-inetRouter
            ip route add 192.168.0.0/16 via 192.168.255.2
            mkdir -p /home/vagrant/.ssh/
            cat /vagrant/vagrant_id_rsa.pub >> /home/vagrant/.ssh/authorized_keys && chmod 0600 /home/vagrant/.ssh/authorized_keys
            chown -R vagrant:vagrant /home/vagrant/.ssh

- hosts: inetRouter2
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for inetRouter2
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth2" ipv4.never-default yes
            nmcli connection modify "System eth1" +ipv4.routes "192.168.0.0/16 192.168.255.2"
            nmcli connection modify "System eth1" ipv4.gateway "192.168.255.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
            nmcli connection up "System eth2"
            extipaddr=$(ip addr show eth2 | grep -Po 'inet \K[\d.]+')
            #iptables -t nat -I PREROUTING -p tcp -d $extipaddr --dport 8080 -j DNAT --to 192.168.0.2:80
            #iptables -I FORWARD -p tcp -d 192.168.0.2 --dport 80 -j ACCEPT
            iptables -t nat -A PREROUTING -d $extipaddr -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.0.2:80
            iptables -t nat -A POSTROUTING -d 192.168.0.2 -p tcp -m tcp --dport 80 -j SNAT --to-source 192.168.255.3
            iptables -t nat -A OUTPUT -d $extipaddr -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.0.2
            iptables -I FORWARD 1 -i eth2 -o eth1 -d 192.168.0.2 -p tcp -m tcp --dport 80 -j ACCEPT

- hosts: centralRouter
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Installing nmap
    yum:
            name: nmap
            state: latest

  - name: Running commands for centralRouter
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.255.1"
            nmcli connection modify "System eth5" +ipv4.routes "192.168.2.0/24 192.168.254.2"
            nmcli connection modify "System eth6" +ipv4.routes "192.168.1.0/24 192.168.253.2"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
            nmcli connection up "System eth5"
            nmcli connection up "System eth6"
            cp /vagrant/knock.sh /home/vagrant/knock.sh && chmod 0700 /home/vagrant/knock.sh && chown vagrant:vagrant /home/vagrant/knock.sh
            mkdir -p /home/vagrant/.ssh/
            cp /vagrant/vagrant_id_rsa /home/vagrant/.ssh/id_rsa && chmod 0600 /home/vagrant/.ssh/id_rsa
            chown -R vagrant:vagrant /home/vagrant/.ssh
    args:
            executable: /bin/bash

- hosts: centralServer
  become: yes
  tasks:
  - name: Running commands for centralServer
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.0.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
            echo "[nginx]" > /etc/yum.repos.d/nginx.repo
            echo "name=nginx repo" >> /etc/yum.repos.d/nginx.repo
            echo "baseurl=http://nginx.org/packages/centos/7/\$basearch/" >> /etc/yum.repos.d/nginx.repo
            echo "gpgcheck=0" >> /etc/yum.repos.d/nginx.repo
            echo "enabled=1" >> /etc/yum.repos.d/nginx.repo
    args:
            executable: /bin/bash
            
  - name: Installing nginx
    yum:
            name: nginx
            state: latest
            update_cache: yes

  - name: Activating nginx
    shell: |
            systemctl start nginx
            systemctl enable nginx

- hosts: office1Router
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for office1Router
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth5" ipv4.gateway "192.168.254.1"
            nmcli connection modify "System eth5" +ipv4.routes "192.168.0.0/24 192.168.254.1"
            nmcli connection modify "System eth5" +ipv4.routes "192.168.1.0/24 192.168.254.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth5"
    args:
            executable: /bin/bash
            
- hosts: office1Server
  become: yes
  tasks:
  - name: Running commands for office1Server
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.2.193"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
    args:
            executable: /bin/bash
            
- hosts: office2Router
  become: yes
  tasks:
  - name: Installing libselinux-python
    yum:
            name: libselinux-python
            state: latest
            update_cache: yes

  - name: Set ip forwarding = 1
    sysctl:
            name: net.ipv4.conf.all.forwarding
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

  - name: Running commands for office2Router
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth4" ipv4.gateway "192.168.253.1"
            nmcli connection modify "System eth4" +ipv4.routes "192.168.0.0/24 192.168.253.1"
            nmcli connection modify "System eth4" +ipv4.routes "192.168.2.0/24 192.168.253.1"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth4"
    args:
            executable: /bin/bash
            
- hosts: office2Server
  become: yes
  tasks:
  - name: Running commands for office2Server
    shell: |
            nmcli connection modify "System eth0" ipv4.never-default yes
            nmcli connection modify "System eth1" ipv4.gateway "192.168.1.193"
            nmcli connection reload
            nmcli connection up "System eth0"
            nmcli connection up "System eth1"
    args:
            executable: /bin/bash

